# Generated by Django 5.0.3 on 2024-08-17 20:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0003_hall_hallscreeningtime_screening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screening',
            name='hall_screening_time',
        ),
        migrations.AddField(
            model_name='screening',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='screening',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tickets.hall'),
        ),
        migrations.AddField(
            model_name='screening',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='HallScreeningTime',
        ),
    ]
