# Generated by Django 5.0.3 on 2024-08-26 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_remove_screening_hall_screening_time_screening_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('seat_in_row', models.IntegerField(blank=True, null=True)),
                ('booked', models.BooleanField(default=True)),
                ('booked_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sold', models.BooleanField(default=False)),
                ('sold_timestamp', models.DateTimeField(blank=True, null=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tickets.screening')),
            ],
        ),
    ]
