# Generated by Django 4.2.16 on 2024-09-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0008_ticket_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='screening',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
